import type { RiskItem } from '@/types';

export const RISK_DATA: Record<string, RiskItem[]> = {
  scaffold: [
    { hazard: '비계 설치 중 추락', riskType: '추락', likelihood: 3, severity: 4, measure: '안전대 착용 의무화, 추락방지망 설치, 작업발판 고정 확인' },
    { hazard: '자재 낙하로 인한 하부 작업자 부상', riskType: '낙하·비래', likelihood: 3, severity: 3, measure: '출입금지 구역 설정, 낙하물 방지망 설치, 안전모 착용' },
    { hazard: '비계 구조물 붕괴', riskType: '붕괴', likelihood: 2, severity: 4, measure: '비계 조립 기준 준수, 정기 점검 실시' },
    { hazard: '공구 및 자재 낙하', riskType: '낙하·비래', likelihood: 3, severity: 3, measure: '공구 안전끈 사용, 작업 전 정리정돈' },
    { hazard: '강풍 시 작업 중 추락', riskType: '추락', likelihood: 2, severity: 4, measure: '풍속 10m/s 이상 시 작업 중지' },
  ],
  rebar_concrete: [
    { hazard: '철근 조립 중 추락', riskType: '추락', likelihood: 3, severity: 4, measure: '안전대 착용, 작업발판 설치, 안전난간 설치' },
    { hazard: '철근에 의한 찔림·베임', riskType: '충돌', likelihood: 3, severity: 2, measure: '철근 보호캡 설치, 보호장갑 착용' },
    { hazard: '콘크리트 타설 시 거푸집 붕괴', riskType: '붕괴', likelihood: 2, severity: 4, measure: '거푸집 동바리 점검, 콘크리트 측압 계산 준수' },
    { hazard: '콘크리트 펌프카 작업 중 충돌', riskType: '충돌', likelihood: 2, severity: 4, measure: '유도자 배치, 장비 반경 내 출입금지' },
    { hazard: '철근 운반 중 근골격계 질환', riskType: '질병', likelihood: 3, severity: 2, measure: '중량물 취급 교육, 보조 운반장비 사용' },
  ],
  excavation: [
    { hazard: '굴착면 붕괴로 매몰', riskType: '붕괴', likelihood: 2, severity: 4, measure: '흙막이 설치, 굴착면 기울기 기준 준수, 매일 점검' },
    { hazard: '굴착기 후진 시 근로자 충돌', riskType: '충돌', likelihood: 3, severity: 4, measure: '유도자 배치, 후방 경보장치 확인' },
    { hazard: '지하 매설물 파손', riskType: '폭발·화재', likelihood: 2, severity: 4, measure: '사전 도면 확인, 탐지기 사용, 수작업 병행' },
    { hazard: '굴착 주변 근로자 추락', riskType: '추락', likelihood: 3, severity: 3, measure: '안전난간 또는 덮개 설치' },
    { hazard: '지반 침하로 인한 인접 구조물 손상', riskType: '붕괴', likelihood: 2, severity: 3, measure: '계측 관리, 침하 모니터링' },
  ],
  high_place: [
    { hazard: '안전대 미착용으로 인한 추락', riskType: '추락', likelihood: 3, severity: 4, measure: '안전대 체결 확인, 생명줄 설치' },
    { hazard: '작업발판 불량으로 인한 추락', riskType: '추락', likelihood: 3, severity: 4, measure: '작업발판 고정 상태 점검, 틈새 방지' },
    { hazard: '고소작업대 전도', riskType: '전도', likelihood: 2, severity: 4, measure: '바닥 평탄 확인, 아웃리거 설치, 과적 금지' },
    { hazard: '공구 및 자재 낙하', riskType: '낙하·비래', likelihood: 3, severity: 3, measure: '공구 안전끈 사용, 낙하물 방지망 설치' },
    { hazard: '강풍에 의한 흔들림', riskType: '추락', likelihood: 2, severity: 4, measure: '풍속 10m/s 이상 시 작업 중지' },
  ],
  heavy_equipment: [
    { hazard: '장비 전도', riskType: '전도', likelihood: 2, severity: 4, measure: '지반 지지력 확인, 과부하 방지, 장비 전담 운전자 지정' },
    { hazard: '후진 시 근로자 충돌', riskType: '충돌', likelihood: 3, severity: 4, measure: '유도자 배치, 후방 카메라 활용, 경보장치 확인' },
    { hazard: '장비 선회 반경 내 협착', riskType: '끼임', likelihood: 3, severity: 4, measure: '작업 반경 출입금지 구역 설정, 신호수 배치' },
    { hazard: '연료 누출로 인한 화재', riskType: '화재', likelihood: 2, severity: 3, measure: '정기 점검, 소화기 비치, 흡연 금지' },
    { hazard: '정비 중 장비 작동', riskType: '끼임', likelihood: 2, severity: 4, measure: '시동키 제거, LOTO 절차 준수' },
  ],
  welding: [
    { hazard: '아크 광선에 의한 눈 손상', riskType: '질병', likelihood: 3, severity: 3, measure: '차광 보안경 착용, 용접 스크린 설치' },
    { hazard: '화재 및 폭발', riskType: '화재', likelihood: 3, severity: 4, measure: '인화성 물질 제거, 소화기 비치, 화기작업 허가' },
    { hazard: '용접 흄 흡입', riskType: '질병', likelihood: 3, severity: 3, measure: '방진마스크 착용, 환기 설비 가동' },
    { hazard: '감전', riskType: '감전', likelihood: 2, severity: 4, measure: '절연장갑 착용, 접지 확인, 누전차단기 설치' },
    { hazard: '비산 불꽃에 의한 화상', riskType: '화상', likelihood: 3, severity: 2, measure: '방염복 착용, 방호 덮개 설치' },
  ],
  electrical: [
    { hazard: '감전', riskType: '감전', likelihood: 3, severity: 4, measure: '정전 작업 원칙, 절연장갑·절연화 착용, 검전기 사용' },
    { hazard: '아크 플래시', riskType: '화상', likelihood: 2, severity: 4, measure: '절연복 착용, 안전거리 유지, 차단기 투입 전 확인' },
    { hazard: '단락으로 인한 화재', riskType: '화재', likelihood: 2, severity: 3, measure: '과부하 방지, 정기 절연 측정' },
    { hazard: '고소 작업 중 추락', riskType: '추락', likelihood: 3, severity: 4, measure: '안전대 착용, 작업대 설치' },
    { hazard: '케이블 반발로 인한 충돌', riskType: '충돌', likelihood: 2, severity: 3, measure: '당김 작업 시 유도자 배치' },
  ],
  waterproof: [
    { hazard: '유해화학물질 노출', riskType: '질병', likelihood: 3, severity: 3, measure: '방독마스크 착용, 환기 설비 가동' },
    { hazard: '밀폐공간 질식', riskType: '질식', likelihood: 2, severity: 4, measure: '산소농도 측정, 강제 환기, 감시자 배치' },
    { hazard: '미끄러짐', riskType: '전도', likelihood: 3, severity: 2, measure: '미끄럼 방지 신발 착용, 바닥 정리' },
    { hazard: '화재', riskType: '화재', likelihood: 2, severity: 3, measure: '토치 사용 시 방화 조치, 소화기 비치' },
    { hazard: '피부 접촉성 질환', riskType: '질병', likelihood: 3, severity: 2, measure: '보호장갑 착용, 피부 보호크림 사용' },
  ],
  painting: [
    { hazard: '유기용제 중독', riskType: '질병', likelihood: 3, severity: 3, measure: '방독마스크 착용, 환기 확보' },
    { hazard: '화재·폭발', riskType: '화재', likelihood: 2, severity: 4, measure: '화기 엄금, 정전기 방지, 환기 설비' },
    { hazard: '고소 작업 중 추락', riskType: '추락', likelihood: 3, severity: 4, measure: '안전대 착용, 작업발판 설치' },
    { hazard: '도료 비산에 의한 눈 손상', riskType: '질병', likelihood: 3, severity: 2, measure: '보안경 착용, 방호 덮개 설치' },
    { hazard: '밀폐공간 질식', riskType: '질식', likelihood: 2, severity: 4, measure: '산소농도 측정, 강제 환기' },
  ],
  demolition: [
    { hazard: '구조물 예상치 못한 붕괴', riskType: '붕괴', likelihood: 2, severity: 4, measure: '해체 계획 수립, 구조 검토, 순차적 해체' },
    { hazard: '분진 흡입', riskType: '질병', likelihood: 3, severity: 3, measure: '방진마스크 착용, 살수 분진 억제' },
    { hazard: '낙하물에 의한 부상', riskType: '낙하·비래', likelihood: 3, severity: 4, measure: '안전모 착용, 출입금지 구역 설정' },
    { hazard: '석면 노출', riskType: '질병', likelihood: 2, severity: 4, measure: '사전 석면 조사, 전문 업체 처리' },
    { hazard: '중장비 협착', riskType: '끼임', likelihood: 2, severity: 4, measure: '신호수 배치, 작업 반경 통제' },
  ],
  interior: [
    { hazard: '사다리 추락', riskType: '추락', likelihood: 3, severity: 3, measure: '사다리 고정, 3점 지지 원칙, 이동식 비계 사용 권장' },
    { hazard: '유해물질 흡입', riskType: '질병', likelihood: 3, severity: 2, measure: '환기 확보, 방진마스크 착용' },
    { hazard: '전동공구 사용 중 충돌', riskType: '충돌', likelihood: 3, severity: 2, measure: '보호장갑 착용, 안전 작동법 교육' },
    { hazard: '미끄러짐·넘어짐', riskType: '전도', likelihood: 3, severity: 2, measure: '정리정돈, 바닥 장애물 제거' },
    { hazard: '눈 이물질 손상', riskType: '질병', likelihood: 3, severity: 2, measure: '보안경 착용' },
  ],
  window: [
    { hazard: '창호 운반 중 파손·부상', riskType: '충돌', likelihood: 3, severity: 3, measure: '보호장갑 착용, 2인 작업 원칙' },
    { hazard: '고소 작업 중 추락', riskType: '추락', likelihood: 3, severity: 4, measure: '안전대 착용, 외부 작업 시 추락방지망' },
    { hazard: '유리 파손에 의한 파편 부상', riskType: '충돌', likelihood: 3, severity: 3, measure: '보호장갑·보안경 착용, 파손 유리 즉시 제거' },
    { hazard: '실란트 유해성분 노출', riskType: '질병', likelihood: 2, severity: 2, measure: '환기 확보, 방독마스크 착용' },
    { hazard: '기계공구 오작동', riskType: '충돌', likelihood: 2, severity: 2, measure: '공구 점검, 안전 작동법 교육' },
  ],
  drainage: [
    { hazard: '굴착면 붕괴', riskType: '붕괴', likelihood: 2, severity: 4, measure: '흙막이 설치, 기울기 준수' },
    { hazard: '관 연결 작업 중 끼임', riskType: '끼임', likelihood: 3, severity: 3, measure: '협착 주의 표지판, 2인 1조 작업' },
    { hazard: '밀폐공간 질식', riskType: '질식', likelihood: 2, severity: 4, measure: '산소농도 측정, 환기, 감시자 배치' },
    { hazard: '미끄러짐', riskType: '전도', likelihood: 3, severity: 2, measure: '안전화 착용, 작업장 정리' },
    { hazard: '중량물 취급 사고', riskType: '충돌', likelihood: 3, severity: 3, measure: '장비 사용, 인력 작업 자세 교육' },
  ],
  road: [
    { hazard: '장비 충돌', riskType: '충돌', likelihood: 3, severity: 4, measure: '유도자 배치, 차량 통제, 안전 조끼 착용' },
    { hazard: '아스팔트 화상', riskType: '화상', likelihood: 3, severity: 2, measure: '내열 장갑·신발 착용, 피부 노출 최소화' },
    { hazard: '롤러 협착', riskType: '끼임', likelihood: 2, severity: 4, measure: '장비 접근금지, 후진 시 유도자 필수' },
    { hazard: '아스팔트 흄 흡입', riskType: '질병', likelihood: 3, severity: 2, measure: '방독마스크 착용, 환기' },
    { hazard: '일반 차량 진입', riskType: '충돌', likelihood: 2, severity: 4, measure: '바리케이드 설치, 안전 표지판' },
  ],
  soil: [
    { hazard: '굴착면 붕괴', riskType: '붕괴', likelihood: 2, severity: 4, measure: '기울기 준수, 흙막이 설치, 일일 점검' },
    { hazard: '중장비 전도', riskType: '전도', likelihood: 2, severity: 4, measure: '지반 지지력 확인, 경사지 작업 주의' },
    { hazard: '덤프트럭 후진 충돌', riskType: '충돌', likelihood: 3, severity: 4, measure: '유도자 배치, 후방 카메라 활용' },
    { hazard: '분진 흡입', riskType: '질병', likelihood: 3, severity: 2, measure: '살수, 방진마스크 착용' },
    { hazard: '지하매설물 손상', riskType: '폭발·화재', likelihood: 2, severity: 4, measure: '사전 탐사, 도면 확인' },
  ],
  foundation: [
    { hazard: '굴착면 붕괴', riskType: '붕괴', likelihood: 2, severity: 4, measure: '흙막이 설치, 기울기 준수' },
    { hazard: '항타기 전도', riskType: '전도', likelihood: 2, severity: 4, measure: '지반 다짐, 장비 수평 설치' },
    { hazard: '진동·소음 피해', riskType: '질병', likelihood: 3, severity: 2, measure: '방진장갑, 귀마개 착용' },
    { hazard: '콘크리트 타설 중 붕괴', riskType: '붕괴', likelihood: 2, severity: 4, measure: '거푸집 점검, 측압 관리' },
    { hazard: '철근 찔림', riskType: '충돌', likelihood: 3, severity: 2, measure: '철근 보호캡 설치' },
  ],
  steel_structure: [
    { hazard: '고소 작업 중 추락', riskType: '추락', likelihood: 3, severity: 4, measure: '안전대 착용, 추락방지망 설치' },
    { hazard: '중량물 낙하', riskType: '낙하·비래', likelihood: 2, severity: 4, measure: '양중 작업 신호수 배치, 출입금지' },
    { hazard: '볼트 체결 중 끼임', riskType: '끼임', likelihood: 2, severity: 2, measure: '보호장갑 착용, 안전 작업법 교육' },
    { hazard: '용접 화재', riskType: '화재', likelihood: 2, severity: 3, measure: '화기작업 허가, 소화기 비치' },
    { hazard: '크레인 신호 오류', riskType: '충돌', likelihood: 2, severity: 4, measure: '무전기 사용, 신호수 전담 배치' },
  ],
  crane: [
    { hazard: '인양물 낙하', riskType: '낙하·비래', likelihood: 2, severity: 4, measure: '와이어 점검, 과부하 방지장치 확인' },
    { hazard: '크레인 전도', riskType: '전도', likelihood: 2, severity: 4, measure: '지반 지지력 확인, 아웃리거 완전 설치' },
    { hazard: '선회 시 충돌', riskType: '충돌', likelihood: 3, severity: 4, measure: '작업 반경 출입금지, 유도자 배치' },
    { hazard: '전선 접촉 감전', riskType: '감전', likelihood: 2, severity: 4, measure: '전선 이격거리 유지, 감시자 배치' },
    { hazard: '신호 오류로 인한 사고', riskType: '충돌', likelihood: 2, severity: 4, measure: '신호수 전담 배치, 무전기 사용' },
  ],
  confined_space: [
    { hazard: '산소 결핍 질식', riskType: '질식', likelihood: 3, severity: 4, measure: '산소농도 측정, 강제 환기, 감시자 배치' },
    { hazard: '유해가스 중독', riskType: '질병', likelihood: 3, severity: 4, measure: '가스 농도 측정, 공기호흡기 착용' },
    { hazard: '추락', riskType: '추락', likelihood: 2, severity: 3, measure: '출입 사다리 고정, 안전대 착용' },
    { hazard: '구조 지연', riskType: '질식', likelihood: 2, severity: 4, measure: '구조 장비 비치, 비상연락망 구축' },
    { hazard: '환기 부족', riskType: '질식', likelihood: 3, severity: 4, measure: '연속 환기 장치 가동' },
  ],
  fire: [
    { hazard: '화재 발생', riskType: '화재', likelihood: 3, severity: 4, measure: '소화기 비치, 인화물질 격리, 화기작업 허가' },
    { hazard: '화상', riskType: '화상', likelihood: 3, severity: 3, measure: '방염복 착용, 소화 담요 비치' },
    { hazard: '연기 흡입', riskType: '질병', likelihood: 3, severity: 3, measure: '방독마스크 착용, 환기 확보' },
    { hazard: '폭발', riskType: '폭발', likelihood: 2, severity: 4, measure: '가연성 물질 관리, 환기, 접지' },
    { hazard: '감전', riskType: '감전', likelihood: 2, severity: 3, measure: '전기 차단 후 작업, 절연장비' },
  ],
  plumbing: [
    { hazard: '관 절단 시 비산물', riskType: '충돌', likelihood: 3, severity: 2, measure: '보안경 착용, 방호 덮개' },
    { hazard: '용접·절단 화재', riskType: '화재', likelihood: 2, severity: 3, measure: '소화기 비치, 인화물질 제거' },
    { hazard: '중량 배관 낙하', riskType: '낙하·비래', likelihood: 2, severity: 3, measure: '지지대 확인, 2인 작업' },
    { hazard: '고소 작업 추락', riskType: '추락', likelihood: 3, severity: 4, measure: '안전대 착용, 작업발판 설치' },
    { hazard: '누설 가스 흡입', riskType: '질병', likelihood: 2, severity: 3, measure: '작업 전 가스 차단, 환기' },
  ],
  hvac: [
    { hazard: '고소 작업 추락', riskType: '추락', likelihood: 3, severity: 4, measure: '안전대 착용, 작업대 설치' },
    { hazard: '냉매 누출 흡입', riskType: '질병', likelihood: 2, severity: 3, measure: '환기 확보, 방독마스크 착용' },
    { hazard: '전기 감전', riskType: '감전', likelihood: 2, severity: 4, measure: '정전 작업, 절연장비 착용' },
    { hazard: '중량물 취급 사고', riskType: '충돌', likelihood: 3, severity: 3, measure: '장비 활용, 2인 작업' },
    { hazard: '덕트 내부 끼임', riskType: '끼임', likelihood: 2, severity: 2, measure: '좁은 공간 작업 주의, 동료 대기' },
  ],
  fire_protection: [
    { hazard: '고소 작업 추락', riskType: '추락', likelihood: 3, severity: 4, measure: '안전대 착용, 작업발판 설치' },
    { hazard: '배관 낙하', riskType: '낙하·비래', likelihood: 2, severity: 3, measure: '지지대 확인, 양중 장비 사용' },
    { hazard: '용접·절단 화재', riskType: '화재', likelihood: 2, severity: 3, measure: '소화기 비치, 화기작업 허가' },
    { hazard: '화학물질 노출', riskType: '질병', likelihood: 2, severity: 2, measure: '방독마스크, 보호장갑 착용' },
    { hazard: '시험 시 압력 파열', riskType: '폭발', likelihood: 2, severity: 4, measure: '압력 테스트 절차 준수, 안전거리 유지' },
  ],
  landscaping: [
    { hazard: '굴착 장비 충돌', riskType: '충돌', likelihood: 3, severity: 3, measure: '유도자 배치, 작업 반경 통제' },
    { hazard: '미끄러짐·넘어짐', riskType: '전도', likelihood: 3, severity: 2, measure: '안전화 착용, 작업장 정리' },
    { hazard: '전동공구 사고', riskType: '충돌', likelihood: 3, severity: 2, measure: '보호구 착용, 안전작동법 교육' },
    { hazard: '중량물 취급', riskType: '충돌', likelihood: 3, severity: 2, measure: '장비 사용, 2인 작업' },
    { hazard: '벌·뱀 등 유해동물', riskType: '질병', likelihood: 2, severity: 2, measure: '작업 전 확인, 보호복 착용' },
  ],
  masonry: [
    { hazard: '벽돌·블록 낙하', riskType: '낙하·비래', likelihood: 3, severity: 3, measure: '낙하물 방지망 설치, 안전모 착용' },
    { hazard: '사다리·비계 추락', riskType: '추락', likelihood: 3, severity: 4, measure: '안전대 착용, 작업발판 설치' },
    { hazard: '분진 흡입', riskType: '질병', likelihood: 3, severity: 2, measure: '방진마스크 착용, 살수' },
    { hazard: '절단기 사용 사고', riskType: '충돌', likelihood: 2, severity: 3, measure: '보안경·장갑 착용, 안전 덮개 확인' },
    { hazard: '근골격계 질환', riskType: '질병', likelihood: 3, severity: 2, measure: '적절한 휴식, 스트레칭' },
  ],
  glass: [
    { hazard: '유리 파손 부상', riskType: '충돌', likelihood: 3, severity: 3, measure: '보호장갑·장화 착용, 취급 주의' },
    { hazard: '운반 중 낙하', riskType: '낙하·비래', likelihood: 3, severity: 3, measure: '진공 흡착기 사용, 2인 작업' },
    { hazard: '고소 설치 추락', riskType: '추락', likelihood: 3, severity: 4, measure: '안전대 착용, 추락방지망' },
    { hazard: '절단 시 비산물', riskType: '충돌', likelihood: 3, severity: 2, measure: '보안경 착용' },
    { hazard: '실란트 유해물질 노출', riskType: '질병', likelihood: 2, severity: 2, measure: '환기 확보, 방독마스크' },
  ],
  insulation: [
    { hazard: '유해물질 흡입', riskType: '질병', likelihood: 3, severity: 3, measure: '방독마스크 착용, 환기 확보' },
    { hazard: '피부 자극', riskType: '질병', likelihood: 3, severity: 2, measure: '보호복·장갑 착용' },
    { hazard: '고소 작업 추락', riskType: '추락', likelihood: 3, severity: 4, measure: '안전대 착용, 작업발판 설치' },
    { hazard: '화재', riskType: '화재', likelihood: 2, severity: 3, measure: '화기 엄금, 소화기 비치' },
    { hazard: '눈 이물질', riskType: '질병', likelihood: 3, severity: 2, measure: '보안경 착용' },
  ],
  signage: [
    { hazard: '고소 작업 추락', riskType: '추락', likelihood: 3, severity: 4, measure: '안전대 착용, 고소작업대 사용' },
    { hazard: '간판 낙하', riskType: '낙하·비래', likelihood: 2, severity: 4, measure: '견고한 고정, 양중 장비 사용' },
    { hazard: '전기 감전', riskType: '감전', likelihood: 2, severity: 4, measure: '정전 작업, 절연장비 착용' },
    { hazard: '전동공구 사용 사고', riskType: '충돌', likelihood: 2, severity: 2, measure: '보호구 착용, 안전 작동법 교육' },
    { hazard: '강풍 시 작업자 추락', riskType: '추락', likelihood: 2, severity: 4, measure: '풍속 10m/s 이상 작업 중지' },
  ],
  elevator: [
    { hazard: '승강로 추락', riskType: '추락', likelihood: 2, severity: 4, measure: '안전난간 설치, 안전대 착용' },
    { hazard: '기계 끼임', riskType: '끼임', likelihood: 2, severity: 4, measure: 'LOTO 절차 준수, 비상정지 장치 확인' },
    { hazard: '중량물 낙하', riskType: '낙하·비래', likelihood: 2, severity: 4, measure: '양중 장비 사용, 출입금지' },
    { hazard: '감전', riskType: '감전', likelihood: 2, severity: 4, measure: '정전 작업, 절연장비 착용' },
    { hazard: '밀폐공간 질식', riskType: '질식', likelihood: 2, severity: 3, measure: '환기 확보, 산소농도 측정' },
  ],
  other: [
    { hazard: '미확인 위험요인', riskType: '기타', likelihood: 2, severity: 3, measure: '작업 전 위험성평가 실시' },
    { hazard: '안전수칙 미준수', riskType: '기타', likelihood: 3, severity: 3, measure: '안전 교육 실시, 관리감독 강화' },
    { hazard: '보호구 미착용', riskType: '기타', likelihood: 3, severity: 3, measure: '보호구 지급 및 착용 확인' },
    { hazard: '의사소통 불량', riskType: '기타', likelihood: 2, severity: 3, measure: '무전기 사용, 신호 체계 통일' },
    { hazard: '작업장 정리정돈 불량', riskType: '전도', likelihood: 3, severity: 2, measure: '5S 활동, 정기 점검' },
  ],
};

export function getRiskData(trade: string): RiskItem[] {
  return RISK_DATA[trade] || RISK_DATA.other;
}
